-- 创建用户查询表
-- 表名: user_queries
-- 描述: 存储用户查询信息及相关状态

CREATE TABLE IF NOT EXISTS user_queries (
    -- 基础字段
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    query_id TEXT NOT NULL UNIQUE,
    user_id TEXT,
    raw_text TEXT NOT NULL,
    
    -- JSON 字段
    parsed_conditions JSONB DEFAULT '{}',
    backend_parameters JSONB DEFAULT '{}',
    
    -- 状态字段
    status TEXT DEFAULT 'initial' CHECK (status IN ('initial', 'clarifying', 'searching', 'completed')),
    clarify_round INTEGER DEFAULT 0,
    match_score DECIMAL(5,2) DEFAULT 0.00,
    
    -- 其他字段
    additional_requirements TEXT,
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 创建索引
CREATE INDEX IF NOT EXISTS idx_user_queries_user_id ON user_queries(user_id);
CREATE INDEX IF NOT EXISTS idx_user_queries_timestamp ON user_queries(timestamp);
CREATE INDEX IF NOT EXISTS idx_user_queries_status ON user_queries(status);

-- 创建更新时间触发器
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_user_queries_updated_at 
    BEFORE UPDATE ON user_queries 
    FOR EACH ROW 
    EXECUTE FUNCTION update_updated_at_column();
