-- 创建推荐结果表
-- 表名: recommendations
-- 描述: 存储每次查询推荐的餐厅列表

CREATE TABLE IF NOT EXISTS recommendations (
    -- 基础 ID
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    
    -- 关联字段（外键）
    query_id TEXT NOT NULL,
    restaurant_id TEXT NOT NULL,
    
    -- 推荐信息
    rank INTEGER NOT NULL,
    final_score DECIMAL(6,4) DEFAULT 0.0000,
    
    -- 分项得分（可选）
    location_score DECIMAL(6,4),
    price_score DECIMAL(6,4),
    rating_score DECIMAL(6,4),
    scene_score DECIMAL(6,4),
    
    -- 时间戳
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    
    -- 约束：query_id + restaurant_id 组合必须唯一
    UNIQUE(query_id, restaurant_id)
);

-- 创建索引
CREATE INDEX IF NOT EXISTS idx_recommendations_query_id ON recommendations(query_id);
