-- 创建餐厅信息表
-- 表名: restaurants
-- 描述: 存储餐厅基本信息、位置、评分、标签等数据

CREATE TABLE IF NOT EXISTS restaurants (
    -- 基础 ID
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurant_id TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    alias TEXT,
    
    -- 位置信息
    city TEXT,
    district TEXT,
    address TEXT,
    latitude DECIMAL(10,8),
    longitude DECIMAL(11,8),
    
    -- 第三方平台
    place_id TEXT,
    google_maps_url TEXT,
    phone TEXT,
    
    -- 分类与菜系
    categories TEXT[],
    cuisine_primary TEXT,
    
    -- 价格信息
    avg_price DECIMAL(8,2),
    price_level INTEGER DEFAULT 1 CHECK (price_level >= 1 AND price_level <= 4),
    
    -- 评分信息
    rating DECIMAL(3,2) DEFAULT 0.00,
    review_count INTEGER DEFAULT 0,
    
    -- 标签系统（文本数组）
    environment_tags TEXT[],
    special_tags TEXT[],
    scene_tags TEXT[],
    signature_dishes TEXT[],
    
    -- 复杂字段（JSON）
    business_hours JSONB,
    attributes JSONB,
    
    -- 计算分数
    popularity_score DECIMAL(6,4) DEFAULT 0.0000,
    scene_match_score DECIMAL(6,4) DEFAULT 0.0000,
    
    -- 时间戳
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 创建索引
CREATE INDEX IF NOT EXISTS idx_restaurants_city ON restaurants(city);
CREATE INDEX IF NOT EXISTS idx_restaurants_district ON restaurants(district);
CREATE INDEX IF NOT EXISTS idx_restaurants_cuisine_primary ON restaurants(cuisine_primary);
CREATE INDEX IF NOT EXISTS idx_restaurants_price_level ON restaurants(price_level);
CREATE INDEX IF NOT EXISTS idx_restaurants_rating ON restaurants(rating);

-- 创建更新时间触发器
CREATE OR REPLACE FUNCTION update_restaurants_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_restaurants_updated_at 
    BEFORE UPDATE ON restaurants 
    FOR EACH ROW 
    EXECUTE FUNCTION update_restaurants_updated_at_column();
