-- 创建餐厅表
CREATE TABLE IF NOT EXISTS restaurants (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  district TEXT,
  address TEXT,
  latitude DECIMAL,
  longitude DECIMAL,
  cuisine TEXT,
  avg_price INTEGER,
  rating DECIMAL(2,1) CHECK (rating >= 1.0 AND rating <= 5.0),
  scene_tags TEXT[],
  feature_tags TEXT[],
  signature_dishes TEXT[],
  image_url TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 为餐厅表添加索引
CREATE INDEX IF NOT EXISTS idx_restaurants_district ON restaurants (district);
CREATE INDEX IF NOT EXISTS idx_restaurants_cuisine ON restaurants (cuisine);
CREATE INDEX IF NOT EXISTS idx_restaurants_avg_price ON restaurants (avg_price);
CREATE INDEX IF NOT EXISTS idx_restaurants_rating ON restaurants (rating);
