-- 创建用户查询记录表
CREATE TABLE IF NOT EXISTS user_queries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  raw_text TEXT,
  parsed_result JSONB,
  selected_district TEXT,
  latitude DECIMAL,
  longitude DECIMAL,
  status TEXT DEFAULT 'pending',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 为用户查询记录表添加索引
CREATE INDEX IF NOT EXISTS idx_user_queries_district ON user_queries (selected_district);
CREATE INDEX IF NOT EXISTS idx_user_queries_status ON user_queries (status);
